---

- hosts: routers
  connection: network_cli
  gather_facts: false

  tasks:
  - name: run show version on remote devices
    ios_command:
      commands: show version
    register: command

  - debug: var=command.stdout_lines


  - name: run show version and check to see if output contains IOS
    ios_command:
      commands: show version
      wait_for: result[0] contains IOS

  - name: run multiple commands
    ios_command:
      commands:
        - show version
        - show interfaces

  - name: run multiple commands and evaluate the output
    ios_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] contains IOS
        - result[1] contains Loopback0